# Each page blueprint must have a title, the title may be different from the file name
# This default blueprint is used to display a page in the Panel whenever a custom page blueprint is missing.
title: Einfache Seite (einfacher Inhalt)

# Each page can have an icon that is shown in page listings when no preview image is available.
icon: 📝

# Page presets are a quick way to set up a standard page layout
# More about page presets:
# - https://getkirby.com/docs/guide/blueprints/presets and
# - https://getkirby.com/docs/reference/panel/presets/page
preset: page

# Custom descriptions of page statuses depending on use case
# More about page statuses: https://getkirby.com/docs/reference/panel/blueprints/page#statuses
status:
  draft:
    label: Entwurf
    text: Die Seite ist als Entwurf gespeichert und nicht veröffentlicht
  unlisted:
    label: Veröffentlicht
    text: Die Seite ist veröffentlicht und wird nicht in den Menüs angezeigt

# Limit subpage display to certain templates in a page preset
pages:
  headline: Blocks
  template: block-info
  empty: Keine Blocks hinzugefügt
  create: block-info
  parent: site.find('blocks')

# A page preset can have a freely defined set of fields
# List of all available field types: https://getkirby.com/docs/reference/panel/fields
fields:
  inMainMenu:
    type: toggle
    width: 1/2
    label: im Hauptmenü anzeigen?
  inFooterMenu:
    type: toggle
    width: 1/2
    label: im Footermenü anzeigen?
  pageContent:
    label: Seiteninhalt
    type: textarea
    size: huge
    validate:
      match: /[^<>${}=%;]$/
